import * as Utils from "./utils";
export interface Event {
    shiftKey: boolean;
    ctrlKey: boolean;
    altKey: boolean;
    metaKey: boolean;
    type: string;
    key: string | null;
    code: string | null;
    x: number;
    y: number;
    clientX: number;
    clientY: number;
    dir: Utils.Loc | null;
    dt: number;
}
export declare type CommandFn = (event: Event) => Promise<boolean>;
export declare var commands: Record<string, CommandFn>;
export declare function addCommand(id: string, fn: CommandFn): void;
export declare type KeyMap = Record<string, CommandFn | boolean>;
export declare type EventMatchFn = (event: Event) => boolean;
export declare const KEYPRESS = "keypress";
export declare const MOUSEMOVE = "mousemove";
export declare const CLICK = "click";
export declare const TICK = "tick";
export declare const MOUSEUP = "mouseup";
export declare function setKeymap(keymap: KeyMap): void;
export declare function hasEvents(): number;
export declare function clearEvents(): void;
export declare function pushEvent(ev: Event): void;
export declare function dispatchEvent(ev: Event, km?: KeyMap | CommandFn): Promise<any>;
export declare function makeTickEvent(dt: number): Event;
export declare function makeKeyEvent(e: KeyboardEvent): Event;
export declare function keyCodeDirection(key: string): Utils.Loc | null;
export declare function ignoreKeyEvent(e: KeyboardEvent): boolean;
export declare var mouse: Utils.XY;
export declare function makeMouseEvent(e: MouseEvent, x: number, y: number): Event;
export declare function pauseEvents(): void;
export declare function resumeEvents(): void;
export declare function nextEvent(ms?: number, match?: EventMatchFn): Promise<Event | null>;
export declare function tickMs(ms?: number): Promise<unknown>;
export declare function nextKeyPress(ms?: number, match?: EventMatchFn): Promise<Event | null>;
export declare function nextKeyOrClick(ms?: number, matchFn?: EventMatchFn): Promise<Event | null>;
export declare function pause(ms: number): Promise<boolean | null>;
export declare function waitForAck(): Promise<boolean | null>;
export declare function loop(keymap: KeyMap): Promise<void>;
